language: node_js
node_js:
  - "lts/*"
script:
  - yarn format
  - yarn tslint
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
