language: node_js
node_js:
  - "lts/*"
script:
  - yarn format
  - yarn tslint
  - yarn test
  - yarn build
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
